name: Cypress Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir arte ASCII personalizada
        run: |
          echo "   ####   ##  ##   ######   ######   #######   #####    #####              ##     ##   ##  ######    #####   ##   ##    ##     ######    ####     #####   ##   ##"
          echo "   ##  ##  ##  ##    ##  ##   ##  ##   ##   #  ##   ##  ##   ##            ####    ##   ##  # ## #   ##   ##  ### ###   ####    # ## #     ##     ##   ##  ###  ##"
          echo "  ##       ##  ##    ##  ##   ##  ##   ## #    #        #                 ##  ##   ##   ##    ##     ##   ##  #######  ##  ##     ##       ##     ##   ##  #### ##"
          echo "  ##        ####     #####    #####    ####     #####    #####            ##  ##   ##   ##    ##     ##   ##  #######  ##  ##     ##       ##     ##   ##  ## ####"
          echo "  ##         ##      ##       ## ##    ## #         ##       ##           ######   ##   ##    ##     ##   ##  ## # ##  ######     ##       ##     ##   ##  ##  ###"
          echo "   ##  ##    ##      ##       ##  ##   ##   #  ##   ##  ##   ##           ##  ##   ##   ##    ##     ##   ##  ##   ##  ##  ##     ##       ##     ##   ##  ##   ##"
          echo "    ####    ####    ####     #### ##  #######   #####    #####            ##  ##    #####    ####     #####   ##   ##  ##  ##    ####     ####     #####   ##   ##"

      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Cache do npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes Cypress (modo headless)
        run: npx cypress run

      - name: Upload de vídeos (em caso de falhas)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload de screenshots (em caso de falhas)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

          